name: Automation Hub Phase

on:
  workflow_dispatch:

jobs:
  get_automation_hub_phase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create dev branch from main
        shell: pwsh
        run: |
          . .\CiCd_Functions.ps1
          $phaseIdStatus = GetPhaseId
          echo $phaseId
