name: Repository Setup

on:
  workflow_dispatch:

jobs:
  create_dev_branch_and_variable:
    runs-on: ubuntu-latest
    #if: github.run_number == 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create dev branch from main
        run: |
          git checkout main
          git pull
          git checkout -b dev
          git push -u origin dev

      - name: Create repository variable
        uses: actions/github-script@v6
        with:
          github-token: \${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.actions.createRepoVariable({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'FOLDER_NAME',
              value: 'Shared'
            })
