name: Analyze Package and Comment on PR with results

on:
  pull_request:
    types: [opened]

jobs:
  analyze-and-comment:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v2

    - name: Analyze Package
      run: |
        uipcli package analyze "C:\Users\matheus.pessanha\Documents\UiPath\CICD_Demo\project.json" --analyzerTraceLevel "Error" --governanceFilePath "C:\Users\matheus.pessanha\Documents\UiPath\CICD_Demo\testWorkflowAnalyzer\uipath.policy.Development.json" --resultPath "results.json"
        
    - name: Read results.json
      id: results
      run: |
          $content = Get-Content "C:\Users\matheus.pessanha\Documents\UiPath\CICD_Demo\testWorkflowAnalyzer\results.json" -Raw
          echo "::set-output name=results::$content"
      shell: pwsh

    - name: Install GitHub CLI on Windows
      run: |
        Invoke-WebRequest -Uri https://github.com/cli/cli/releases/download/v2.45.0/gh_2.45.0_windows_amd64.msi -OutFile ghcli.msi
        Start-Process msiexec.exe -Wait -ArgumentList '/i', 'ghcli.msi', '/quiet'
      shell: pwsh

    - name: Comment on PR using GitHub CLI
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: pwsh
      run: |
         $results = @"
          **UiPath CLI Analysis Results**
         ${{ steps.read_results.outputs.results }}
         "@
         
          gh pr comment ${{ github.event.pull_request.number }} --body "$results"
         
      
